namespace ProcessKit

/// How a process run concluded.
[<RequireQualifiedAccess; NoComparison>]
type Outcome =

    /// Exited with the given code.
    | Exited of ExitCode: int

    /// Terminated by a signal (Unix). `None` when the signal number is unavailable.
    | Signalled of SignalNumber: int option

    /// Killed because it exceeded its timeout.
    | TimedOut

    /// The process concluded, but its actual exit status could not be observed — a native API
    /// failure (e.g. Windows `DuplicateHandle`/`GetExitCodeProcess`), or a POSIX reap race whose
    /// winner never reported the real decoded status within a grace period. `Reason` is a short,
    /// human-readable explanation for logs/diagnostics. This is deliberately NOT a sentinel for a
    /// clean exit — never fabricate `Exited 0` for a process whose outcome genuinely was not seen;
    /// use this case instead. Always treated as a failure (`IsAcceptedBy` is always `false`, like
    /// `Signalled`/`TimedOut`), and never itself a `-1`/`0` stand-in.
    | Unobserved of Reason: string

    /// The exit code, or `None` for a signal kill, timeout, or unobserved outcome (never a `-1` sentinel).
    member this.Code =
        match this with
        | Outcome.Exited code -> Some code
        | Outcome.Signalled _
        | Outcome.TimedOut
        | Outcome.Unobserved _ -> None

    /// The terminating signal, when known.
    member this.Signal =
        match this with
        | Outcome.Signalled signal -> signal
        | _ -> None

    /// Whether this outcome counts as success under `okCodes` — an exit with an accepted code (a
    /// signal kill, a timeout, or an unobserved outcome never does). The single accepted-code rule
    /// shared by `ProcessResult.IsSuccess`, pipeline pipefail classification, and the stdin-error
    /// success gate, so they cannot drift.
    member internal this.IsAcceptedBy(okCodes: int list) =
        match this with
        | Outcome.Exited code -> List.contains code okCodes
        | Outcome.Signalled _
        | Outcome.TimedOut
        | Outcome.Unobserved _ -> false

// `IsExited` / `IsSignalled` / `IsTimedOut` / `IsUnobserved` tester properties are generated by the
// F# compiler for each union case; consume `outcome.IsTimedOut` directly.
