namespace ProcessKit

/// How a process run concluded.
[<RequireQualifiedAccess; NoComparison>]
type Outcome =

    /// Exited with the given code.
    | Exited of ExitCode: int

    /// Terminated by a signal (Unix). `None` when the signal number is unavailable.
    | Signalled of SignalNumber: int option

    /// Killed because it exceeded its timeout.
    | TimedOut

    /// The exit code, or `None` for a signal kill or timeout (never a `-1` sentinel).
    member this.Code =
        match this with
        | Outcome.Exited code -> Some code
        | Outcome.Signalled _
        | Outcome.TimedOut -> None

    /// The terminating signal, when known.
    member this.Signal =
        match this with
        | Outcome.Signalled signal -> signal
        | _ -> None

// `IsExited` / `IsSignalled` / `IsTimedOut` tester properties are generated by the F#
// compiler for each union case; consume `outcome.IsTimedOut` directly.
