<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<AssemblyName>ProcessKit.Fuzz</AssemblyName>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<AssemblySearchPaths>$(AssemblySearchPaths);$(MainProjectDir)bin\$(Configuration)\$(TargetFramework);$(RepoRoot)src\ProcessKit.Testing\bin\$(Configuration)\$(TargetFramework)</AssemblySearchPaths>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Program.fs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FSharp.Core" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="SharpFuzz" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ProcessKit" />
		<Reference Include="ProcessKit.Testing" />
	</ItemGroup>

</Project>
